language: c++
dist: bionic
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - cmake
      - openssl
script:
  - export CC=clang-11; export CXX=clang++-11;
  - mkdir build && cd build && cmake .. && make && make test
