language: c++
dist: bionic
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - autotools-dev
      - automake
      - cmake
      - aclocal
script:
  - export CC=clang-9; export CXX=clang++-9;
  - mkdir build && cd build && cmake .. && make && make test && cd ..
  - mkdir build-release && cd build-release && cmake -DCMAKE_BUILD_TYPE=Release -DWITH_STATIC=ON .. && make && make test
