language: C++
dist: Bionic
os: Linux
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - clang-9
      - cmake
      - openssl
script:
  - export CC=clang-9; export CXX=clang++-9;
  - mkdir build && cd build && cmake .. && make && make test
